# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
submission_information({
    add_id_info_uses_idfa: false
})
submit_for_review(true)
reject_if_possible(true)
automatic_release(true)
metadata_path("./metadata")
skip_screenshots(true)
force(true)
run_precheck_before_submit(false)
release_notes(
    {
        'en-CA': 'Bug fixes and performance improvements',
    }
)
